### ISSUE TITLE
move development here?

### ISSUE THREAD

**Issue by kostrzewa** [qcdcode/quda#1]
@urbach should we perhaps move the ndeg-twisted-clover development here?

**Comment by kostrzewa** [comment]
At some point the work should switch directly to lattice/quda anyway in order to benefit from access to their continuous integration infrastructure.

**Comment by urbach** [comment]
> At some point the work should switch directly to lattice/quda anyway in order to benefit from access to their continuous integration infrastructure.

yes, we can move it. I'd also prefer to have it directly at
lattice/quda, but there I don't have write access. I can ask Kate.

**Comment by kostrzewa** [comment]
Yes, getting write access is as easy as asking Kate, Simone and I have it anyway and I believe Kyriacos does too.

**Comment by kostrzewa** [comment]
I've force-pushed your branch here and have started some "documentation" https://github.com/qcdcode/quda/wiki/ndeg-twisted-clover-kernel-and-testing
